name: DanielKoziara.pl
title: Programista do wynajęcia - DanielKoziara.pl
email: kontakt@danielkoziara.pl
description: >-
  Blog o technologiach do tworzenia stron internetowych. Znajdziesz też trochę
  informacji o web design'u.
baseurl: 'https://danielkoziara.pl/'
paginate: 12
google_analytics: UA-129381766-1
favicon: assets/images/favicon.ico
lang: pl_PL
disqus: danielkoziara
paginate_path: '/strona/:num'
markdown: kramdown
permalink: '/:slug'
exclude:
  - _screenshots
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
plugins:
  - jekyll-admin
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
